name: Preprocessing Data

on:
  push:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn imbalanced-learn

    - name: Run Preprocessing Script
      run: |
        python preprocessing/automate_rtaufik27.py

    - name: Upload Preprocessed Dataset
      uses: actions/upload-artifact@v4
      with:
        name: preprocessed-employee-data
        path: preprocessing/employee_preprocessing.csv
